language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn build && npx semantic-release
