language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: test
      node_js: lts/*
      script: yarn test
    - stage: percy
      node_js: lts/*
      script: yarn ci:test:visual
    - stage: release
      node_js: lts/*
      script: cd slang && yarn build && npx semantic-release
    - stage: research-release
      if: branch = research
      node_js: lts/*
      script: cd slang && yarn build && npx semantic-release --branch research
