language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: build
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
