language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: test
      node_js: lts/*
      script: yarn test
    - stage: percy
      node_js: lts/*
      script: yarn ci:test:visual
      if: NOT (branch = master)
    - stage: release
      node_js: lts/*
      script: cd slang && yarn build && npx semantic-release
